name: CI

on:
  push:
    branches:
      - main


jobs:
  docker:
    runs-on: ubuntu-latest


    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: login docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.SOCKER_UERNAME}}
          passsword: ${{secrets.DOKCER_PASSWORD}}

        
      - name: build docker
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/docker-ci-demo:latest .
      
      - name: push dokcer 
        run: |
          docker push ${{secrets.DOCKER_PASSWORD}}/docker-ci-demo:latest

          