name: dispatch practice

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter application version"
        required: true

      environment:
        description: "Enter deployment environment"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: print deployment details
        run: |
          echo "Deploying Version: ${{ github.event.inputs.version }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
