name: Hello Workflow

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: print
        run: echo "hello DEVOPS"
      - name: install
        run: npm install
      - name: test
        run: npm test
